{"grading_finished_at": "2022-09-10T11:15:59.714633", "grading_duration_in_seconds": 2, "learner_score": 55, "total_available": 60, "num_test_cases": 6, "num_passed_cases": 5, "num_failed_cases": 1, "results": [{"test_case_name": "tc-01", "available_points": 5, "points": 5, "pass": true, "message": ""}, {"test_case_name": "tc-02", "available_points": 10, "points": 10, "pass": true, "message": ""}, {"test_case_name": "tc-03", "available_points": 10, "points": 10, "pass": true, "message": ""}, {"test_case_name": "tc-04", "available_points": 15, "points": 15, "pass": true, "message": ""}, {"test_case_name": "tc-05", "available_points": 5, "points": 0, "pass": false, "message": "Traceback (most recent call last):\n  File \"/tmp/ipykernel_268688/2943434076.py\", line 7, in <cell line: 1>\n    tc.assertEqual(f, 5.25)\n  File \"/opt/tljh/user/lib/python3.9/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/tljh/user/lib/python3.9/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 5.0 != 5.25\n"}, {"test_case_name": "tc-06", "available_points": 15, "points": 15, "pass": true, "message": ""}]}